fix: add local flag to fides run

diff --git a/.github/workflows/fides_ci.yml b/.github/workflows/fides_ci.yml
--- a/.github/workflows/fides_ci.yml
+++ b/.github/workflows/fides_ci.yml
@@ -23,31 +23,31 @@ jobs:
       # For the purposes of this example, we are hosting a Fides Server in this CI job
       # In a production environment, this service would not be here and an end user would point 
       # the Fides Scan and Fides evaluate commands to a production instance hosted elsewhere. 
-      postgresfides:
-        image: postgres:latest
-        env:
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-          POSTGRES_DB: fides
-        ports:
-          - 5432:5432
-        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
+      # postgresfides:
+      #   image: postgres:latest
+      #   env:
+      #     POSTGRES_USER: postgres
+      #     POSTGRES_PASSWORD: postgres
+      #     POSTGRES_DB: fides
+      #   ports:
+      #     - 5432:5432
+      #   options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
       
       
-      fides:
-        image: ethyca/fides
-        env:
-          FIDES__DATABASE__SERVER: postgresfides
-          FIDES__DATABASE__USER: postgres
-          FIDES__DATABASE__PASSWORD: postgres
-          FIDES__DATABASE__PORT: 5432
-          FIDES__DATABASE__DB: fides
-          FIDES__SECURITY__APP_ENCRYPTION_KEY: OLMkv91j8DHiDAULnK5Lxx3kSCov30b3
-          FIDES__SECURITY__OAUTH_ROOT_CLIENT_ID: cicdclient
-          FIDES__SECURITY__OAUTH_ROOT_CLIENT_SECRET: cicdsecret
-        ports:
-          - 8080:8080
-        options: --health-cmd "curl --fail http://localhost:8080/health || exit 1" --health-interval 10s --health-timeout 10s --health-retries 10
+      # fides:
+      #   image: ethyca/fides
+      #   env:
+      #     FIDES__DATABASE__SERVER: postgresfides
+      #     FIDES__DATABASE__USER: postgres
+      #     FIDES__DATABASE__PASSWORD: postgres
+      #     FIDES__DATABASE__PORT: 5432
+      #     FIDES__DATABASE__DB: fides
+      #     FIDES__SECURITY__APP_ENCRYPTION_KEY: OLMkv91j8DHiDAULnK5Lxx3kSCov30b3
+      #     FIDES__SECURITY__OAUTH_ROOT_CLIENT_ID: cicdclient
+      #     FIDES__SECURITY__OAUTH_ROOT_CLIENT_SECRET: cicdsecret
+      #   ports:
+      #     - 8080:8080
+      #   options: --health-cmd "curl --fail http://localhost:8080/health || exit 1" --health-interval 10s --health-timeout 10s --health-retries 10
     steps:
       - uses: actions/checkout@v2
       - name: Set up Python
@@ -87,6 +87,6 @@ jobs:
           conn.close()
           "
       - name: Scan Database and validate that all fields are accounted for
-        run: fides scan dataset db --connection-string postgresql://postgres:postgres@localhost:5433/postgres_example
+        run: fides --local scan dataset db --connection-string postgresql://postgres:postgres@localhost:5433/postgres_example
       - name: Evaluation
-        run: fides evaluate .fides/
+        run: fides --local evaluate .fides/
